name: dalil_2020_app
description: "Dalil-2020 App"
version: 1.9.1+2

environment:
  sdk: ^3.6.0

dependencies:
  # Core Flutter SDK
  flutter:
    sdk: flutter
  intl: ^0.20.2




  # Networking
  dio: ^5.7.0
  dartz: ^0.10.1


  # Firebase
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1



  # Utilities
  fluttertoast: ^8.2.10
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.5
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  dynamic_height_grid_view: ^0.0.4
  flutter_staggered_grid_view: ^0.7.0
  another_stepper: ^1.2.2
  flutter_rating_bar: ^4.0.1
  dropdown_button2: ^2.3.9
  password_strength_checker: ^1.2.4
  google_fonts: ^6.2.1
  easy_stepper: ^0.8.5+1
  table_calendar: ^3.1.3
  flutter_spinner_time_picker: ^0.2.1
  flutter_cupertino_date_picker_fork: ^1.0.7
  rate: ^0.0.2
  # LOCATION
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  # UI - TOOLS
  share_plus: ^10.1.3
  skeletonizer: ^2.1.0+1
  flutter_slidable: ^4.0.0
  pin_code_fields: ^8.0.1
  flutter_intl_phone_field: ^0.0.4
  dotted_border: ^2.1.0
  file_picker: ^9.0.0
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  lottie: ^3.3.1
  video_player: ^2.9.2
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  flutter_svg_provider: ^1.0.7
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  pusher_channels_flutter: ^2.5.0
  refresh_loadmore: ^2.0.7
  geolocator: ^13.0.2
  quiver: ^3.2.2
  custom_info_window: ^1.0.1
  flutter_tawkto: ^0.0.5
  smooth_page_indicator: ^1.2.1
  ansicolor: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_of_app.png"
  adaptive_icon_foreground: "assets/images/logo_of_app.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/videos/
    - assets/jsons/
    - assets/icons/
    - assets/images/
    - assets/translations/
  fonts:
     - family: STV
       fonts:
        - asset: assets/fonts/stv.ttf

     - family: Poppins
       fonts:
         - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/poppins/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/poppins/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/poppins/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/poppins/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/poppins/Poppins-Black.ttf
           weight: 900