name: Deploy Android to Firebase App Distribution (Unsigned)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLESERVICEPLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools --prefix /usr/local
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/apk/release/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"
